# background: #0a0a0a
# surface:    #111111
# surface-2:  #161616
# text:       #d8dec8
# muted:      #7e876f
# accent:     #b7d98c
# accent-2:   #8fae63
# urgent:     #d98c8c

[bar/main]
width = 100%
height = 28
background = #0a0a0a
foreground = #111111

modules-left = i3
modules-right = cpu memory date

font-0 = monospace;2

[module/i3]
type = internal/i3

[module/cpu]
type = internal/cpu
format = CPU %percentage%%

[module/memory]
type = internal/memory
format = RAM %percentage_used%%

[module/date]
type = internal/date
date = %H:%M

