background{
monitor = DP-2
color = rgba(25, 20, 20, 1.0)

blur_passes = 0
blur_size = 7
noise = 0.0117
contrast = 0.
brightness = -.8712
vibrancy = 0.1696
vibrancy_darkness = 0.0
}

label {
    monitor = DP-2
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(230, 236, 240, 0.95)
    font_size = 96
    font_family = sans

    position = 0, 155
    halign = center
    valign = center
}

label {
    monitor = DP-2
    text = cmd[update:60000] date +"%A, %B %d"
    color = rgba(143, 143, 143, 0.9)
    font_size = 24
    font_family = sans

    position = 0, 75
    halign = center
    valign = center
}

input-field {
    monitor = DP-2
    size = 22%, 5.5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.22)

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgba(230, 236, 240, 0.95)
    fade_on_empty = false
    placeholder_text = <i>Enter password</i>
    rounding = 18

    position = 0, -115
    halign = center
    valign = center
}
