# preload = ~/.config/backgrounds/blackGreenComputers.jpeg
# wallpaper = , ~/.config/backgrounds/blackGreenComputers.jpeg

# cover    → aspect ratio behouden, scherm volledig vullen, randen afsnijden
# contain  → hele afbeelding zichtbaar, maar met lege/zwarte randen
# fill     → volledig scherm vullen door te stretchen
# tile     → afbeelding herhalen

wallpaper {
monitor = DP-2
path = ~/.config/backgrounds/cropped-lego-head.png
fit_mode = fill
}

wallpaper {
monitor = DP-3
path = ~/.config/backgrounds/legoSmiley.png
fit_mode = contain
}

splash = false
ipc = off

