# preload = ~/.config/backgrounds/blackGreenComputers.jpeg
# wallpaper = , ~/.config/backgrounds/blackGreenComputers.jpeg

wallpaper {
monitor = DP-2
path = ~/.config/backgrounds/blackGreenComputers.jpeg
fit_mode = cover
}

wallpaper {
monitor = DP-3
path = ~/.config/backgrounds/blackGreenComputers.jpeg
fit_mode = cover
}

splash = false
ipc = off
