set -g status-bg "#B7D4B8"

unbind C-b
set-option -g prefix C-v
bind-key C-v send-prefix

bind | split-window -h
bind - split-window -v

unbind '"'
unbind %

bind-key r source-file ~/.tmux.conf \; display-message "config reloaded"

set-option -g allow-rename off
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -s escape-time 0

bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
